messageDigit = [
    [0, 2],
    [2, 12],
    [12, 16],
    [16, 19],
    [19, 23],
    [23, 25],
    [25, 41],
    [41, 45],
    [45, 47],
    [47, 51],
    [51, 55],
    [55, 71],
    [71, 88],
    [88, 92],
    [92, 96],
    [96, 101],
    [101, 122]
]

fieldLen = [
    2,
    10,
    4,
    3,
    4,
    2,
    5,
    5,
    6,
    4,
    2,
    4,
    4,
    16,
    17,
    4,
    4,
    5,
    21]

fieldNames = [
    'message type',
    'from (country)',
    'from (provider)',
    'event category',
    'event subcategory',
    'severity',
    'onset',
    'expected duration',
    'guidance library',
    'response guide',
    'instruction',
    'latitude',
    'longitude',
    'semi-major axis',
    'semi-minor axis',
    'azimuth',
    'parameter type']

fields = [
    ['alert',
     'update',
     'test',
     'cancel'],
    ['none'],
    ['none'],
    ['geo1',
     'geo2',
     'met1',
     'met2',
     'safety',
     'security',
     'transport',
     'fire'],
    [
        ['earthquake',
         'tsunami',
         'sinkhole',
         'avalanche',
         'satellite debris',
         'pyroclastic flow',
         'lava flow',
         'volcanic mud flow',
         'glacial ice avalanche',
         'tidal wave',
         'landslide'],
        ['debris flow',
         'ash fall',
         'volcanic eruption'],
        ['typhoon',
         'tornado',
         'storm',
         'hail',
         'dust storm',
         'storm surge',
         'heavy rain',
         'black ice',
         'high uv radiation',
         'plague of insects',
         'pest infestation',
         'epizootic',
         'contaminated drinking water'],
        ['heavy snow',
         'flood',
         'lightning',
         'extreme heat',
         'frost',
         'derecho',
         'fog',
         'snow drifts'],
        ['chemical hazard',
         'biological hazard',
         'radiological hazard',
         'nuclear hazard',
         'explosive hazard',
         'unidentified animal',
         'chemical accident',
         'hazardous material accident',
         'demonstration',
         'odour nuisance',
         'major event',
         'risk of infection',
         'noise pollution',
         'food safety alert',
         'safety warning'],
        ['shooting',
         'ballistic missile attack',
         'guerrilla attack',
         'large-scale terrorism',
         'air strike',
         'hijack',
         'chemical attack',
         'explosive attack',
         'nuclear weapon attack',
         'life threatening situation',
         'health hazard',
         'first/second world war bomb',
         'bomb discovery',
         'it system outage'],
        ['maritime disaster',
         'train accident',
         'bridge collapse',
         'aircraft crash',
         'oil spill',
         'road traffic accident',
         'traffic alert',
         'gas supply outage',
         'emergency number outage',
         'telephone line outage',
         'power outage'],
        ['forest fire',
         'structure fire',
         'solar storm',
         'missing person',
         'air pollution',
         'building collapse',
         'dam failure',
         'dike failure',
         'fire gases',
         'risk of fire',
         'gas leak',
         'nuclear power station accident',
         'raw sewage',
         'siren test',
         'warning',
         'acid rain']],
    ['extreme',
     'severe',
     'moderate',
     'minor'],
    ['none'],
    ['no duration',
     'duration < 0.25 hour',
     '0.25 <= duration < 0.5 hour',
     '0.5 <= duration < 0.75 hour',
     '0.75 <= duration < 1 hour',
     '1 <= duration < 1.5 hour ',
     '1.5 <= duration < 2 hour',
     '2 <= duration < 3 hour',
     '3 <= duration < 4 hour',
     '4 <= duration < 6 hour',
     '6 <= duration < 8 hour',
     '8 <= duration < 12 hour',
     '12 <= duration < 18 hour',
     '18 <= duration < 24 hour',
     '24 <= duration < 48 hour',
     '45 <= duration hour'],
    ['international guidance library',
     'national guidance library',
     'regional guidance library',
     'new guidance library under validation'],
    ['none'],
    ['test'],
    ['none'],
    ['none'],
    ['316',
     '635',
     '1277',
     '2565',
     '5154',
     '10355',
     '20806',
     '41803',
     '83993',
     '168761',
     '339081',
     '681292',
     '1368875',
     '2750388',
     '5526170',
     '11103363'],
    ['316',
     '635',
     '1277',
     '2565',
     '5154',
     '10355',
     '20806',
     '41803',
     '83993',
     '168761',
     '339081',
     '681292',
     '1368875',
     '2750388',
     '5526170',
     '11103363'],
    ['none'],
    ['none']
]

